---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dual-deployment-operator-cc-sap-v1alpha1-dualdeploymentoperator
  failurePolicy: Fail
  name: vdualdeploymentoperator-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dual-deployment-operator.cc.sap
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dualdeploymentoperators
  sideEffects: None
