# This rule is not used by the project dual-deployment-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dual-deployment-operator.cc.sap resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dual-deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: dualdeploymentoperator-viewer-role
rules:
- apiGroups:
  - dual-deployment-operator.cc.sap
  resources:
  - dualdeploymentoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dual-deployment-operator.cc.sap
  resources:
  - dualdeploymentoperators/status
  verbs:
  - get
