//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionPolicy) DeepCopyInto(out *DeletionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionPolicy.
func (in *DeletionPolicy) DeepCopy() *DeletionPolicy {
	if in == nil {
		return nil
	}
	out := new(DeletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DualDeploymentOperator) DeepCopyInto(out *DualDeploymentOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DualDeploymentOperator.
func (in *DualDeploymentOperator) DeepCopy() *DualDeploymentOperator {
	if in == nil {
		return nil
	}
	out := new(DualDeploymentOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DualDeploymentOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DualDeploymentOperatorList) DeepCopyInto(out *DualDeploymentOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DualDeploymentOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DualDeploymentOperatorList.
func (in *DualDeploymentOperatorList) DeepCopy() *DualDeploymentOperatorList {
	if in == nil {
		return nil
	}
	out := new(DualDeploymentOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DualDeploymentOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DualDeploymentOperatorSpec) DeepCopyInto(out *DualDeploymentOperatorSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.RemoteKubeconfig = in.RemoteKubeconfig
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]Transformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DeletionPolicy = in.DeletionPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DualDeploymentOperatorSpec.
func (in *DualDeploymentOperatorSpec) DeepCopy() *DualDeploymentOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(DualDeploymentOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DualDeploymentOperatorStatus) DeepCopyInto(out *DualDeploymentOperatorStatus) {
	*out = *in
	if in.HostResources != nil {
		in, out := &in.HostResources, &out.HostResources
		*out = make([]ResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteResources != nil {
		in, out := &in.RemoteResources, &out.RemoteResources
		*out = make([]ResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DualDeploymentOperatorStatus.
func (in *DualDeploymentOperatorStatus) DeepCopy() *DualDeploymentOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(DualDeploymentOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterKindsSpec) DeepCopyInto(out *FilterKindsSpec) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterKindsSpec.
func (in *FilterKindsSpec) DeepCopy() *FilterKindsSpec {
	if in == nil {
		return nil
	}
	out := new(FilterKindsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmSource) DeepCopyInto(out *HelmSource) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.HostValues != nil {
		in, out := &in.HostValues, &out.HostValues
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteValues != nil {
		in, out := &in.RemoteValues, &out.RemoteValues
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmSource.
func (in *HelmSource) DeepCopy() *HelmSource {
	if in == nil {
		return nil
	}
	out := new(HelmSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONPatchOp) DeepCopyInto(out *JSONPatchOp) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatchOp.
func (in *JSONPatchOp) DeepCopy() *JSONPatchOp {
	if in == nil {
		return nil
	}
	out := new(JSONPatchOp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeSource) DeepCopyInto(out *KustomizeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeSource.
func (in *KustomizeSource) DeepCopy() *KustomizeSource {
	if in == nil {
		return nil
	}
	out := new(KustomizeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageWebhookConfigsForInjectorSpec) DeepCopyInto(out *PackageWebhookConfigsForInjectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageWebhookConfigsForInjectorSpec.
func (in *PackageWebhookConfigsForInjectorSpec) DeepCopy() *PackageWebhookConfigsForInjectorSpec {
	if in == nil {
		return nil
	}
	out := new(PackageWebhookConfigsForInjectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchSpec) DeepCopyInto(out *PatchSpec) {
	*out = *in
	out.Target = in.Target
	if in.StrategicMerge != nil {
		in, out := &in.StrategicMerge, &out.StrategicMerge
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.JSONPatch != nil {
		in, out := &in.JSONPatch, &out.JSONPatch
		*out = make([]JSONPatchOp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchSpec.
func (in *PatchSpec) DeepCopy() *PatchSpec {
	if in == nil {
		return nil
	}
	out := new(PatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteKubeconfigRef) DeepCopyInto(out *RemoteKubeconfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteKubeconfigRef.
func (in *RemoteKubeconfigRef) DeepCopy() *RemoteKubeconfigRef {
	if in == nil {
		return nil
	}
	out := new(RemoteKubeconfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteWebhookURLSpec) DeepCopyInto(out *RewriteWebhookURLSpec) {
	*out = *in
	if in.TargetKinds != nil {
		in, out := &in.TargetKinds, &out.TargetKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteWebhookURLSpec.
func (in *RewriteWebhookURLSpec) DeepCopy() *RewriteWebhookURLSpec {
	if in == nil {
		return nil
	}
	out := new(RewriteWebhookURLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Kustomize != nil {
		in, out := &in.Kustomize, &out.Kustomize
		*out = new(KustomizeSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transformation) DeepCopyInto(out *Transformation) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(PatchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RewriteWebhookURL != nil {
		in, out := &in.RewriteWebhookURL, &out.RewriteWebhookURL
		*out = new(RewriteWebhookURLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FilterKinds != nil {
		in, out := &in.FilterKinds, &out.FilterKinds
		*out = new(FilterKindsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PackageWebhookConfigsForInjector != nil {
		in, out := &in.PackageWebhookConfigsForInjector, &out.PackageWebhookConfigsForInjector
		*out = new(PackageWebhookConfigsForInjectorSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transformation.
func (in *Transformation) DeepCopy() *Transformation {
	if in == nil {
		return nil
	}
	out := new(Transformation)
	in.DeepCopyInto(out)
	return out
}
